development:
  adapter: postgresql
  encoding: unicode
  database: mywebsite.dev
  pool: 5
  username: amostofi

test:
  adapter: postgresql
  encoding: unicode
  database: mywebsite.test
  pool: 5
  username: amostofi
