# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c786ccae47f0407d6dfd9af0841a6ce7dea83ea5b84bfd4eb72a95a5177105a7cd8532cf602b4f2f5e34f6b16706f768022dae72d8f23156d09755c573e0a434

test:
  secret_key_base: bf724377734ae0a5284483da070b6a235e6b55af2cec4e2b219a016611104338c23cee22a65e4813025654394d7da995e6248c66b7f488d7a7d4022fb907686c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
